#jupyter nbconvert --execute --to html test-run-with-command-line.ipynb
#jupyter nbconvert --to ipynb --execute ./test-run-with-command-line.ipynb --output "1403-08-27.ipynb"
log:
    mode: both
    # Note: The name and path of the log file are set in the settings section for each code.
    filename_prefix: Training_on_Merged_datasets
    filename: now # if set to "now", the current date set as the logfile name.
    filepath: None # Set in the subset config.
    level: INFO
    format: "%(asctime)s - %(levelname)s - %(message)s"

dataset:
    path: F:\DataSets-Local\Merged_All_DataSets_2025-07-10 (Ahar-Ilam-Kaki-Qeshm)
    parameters:
        dimension_order: CW
        component_order: ZNE
        sampling_rate: 100
        measurement: velocity
        unit: counts
        instrument_response: not restituted
    spliter:
        train: 0.8
        dev: 0.1
        test: 0.1
    

training:
    num_workers: 0 # The number of threads used for loading data
    hyperparameters:
        batch_size: 256
        learning_rates: [1e-2, 1e-3]
        epochs_for_each_learning_rate: [1, 1]
        manual_seed: 42
        norm: peak
        phases: 'NPS'
        lr_scheduler:
            ReduceLROnPlateau:
                factor: 0.2
                patience: 3
    dataset:
        path: C:\Users\ikahbasi\Documents\ikahbasi-PhD\DataSets-Local\Kaki-Dataset_2025-04-23T11-38-30
        dimension_order: CW
        component_order: ZNE
        sampling_rate: 100
        suffle: True
    output_model:
        filepath: F:\Models\PhaseNet_Trained_single_networks
        filename_prefix: PhaseNet_Kaki
        version_str: '14040318_1800_PS-Pairs'
