#jupyter nbconvert --execute --to html test-run-with-command-line.ipynb
#jupyter nbconvert --to ipynb --execute ./test-run-with-command-line.ipynb --output "1403-08-27.ipynb"
log:
    mode: both
    # Note: The name and path of the log file are set in the settings section for each code.
    filename_prefix: Ahar_mk-dataset
    filename: now # if set to "now", the current date set as the logfile name.
    filepath: None # Set in the subset config.
    level: INFO
    format: "%(asctime)s - %(levelname)s - %(message)s"

mk_dataset:
    parameters:
        dimension_order: CW
        component_order: ZNE
        sampling_rate: 100
        measurement: velocity
        unit: counts
        instrument_response: not restituted
    cut_time:
        before: 10
        after: 60
    zero_pad:
        before: 0
        after: 0
    noisepad:
        apply: False
        before: 0
        after: 0
        std_start: 2
        std_end: 2
    filter:
        apply: False
        low: 1
        high: 10
    autolabeling: False
    save_streams: False
    path:
        inputs:
            catalog: F:\Local_Network_Data-Raw\IIEES_2006-2023\BIN_2004_2024-Cleaned.out
            stream_root: F:\Local_Network_Data-Raw\IIEES_2006-2023\Waveforms
            network_details: F:\Network_Details\IIEES-BIN.csv
            stream_pattern: '*/{time.year}-{time.month:02}-{time.day:02}*' # Note: Check Network!
        outputs:
            dataset: 'F:\DataSets-Local\IIEES-BIN-Dataset_{datetime_str}'
            log:
                filename: now
